### ISSUE TITLE
請問 revamp 中的 api/config.js 的內容應為?

### ISSUE THREAD

**Issue by aqutw** [twreporter/twreporter-react#224]
我想試跑出(或貢獻代碼) revamp 新版畫面。
`npm run dev` 後，遇到 Timeout issue 如下 --- **黃方框是我 debug 的 string** :
![image](https://cloud.githubusercontent.com/assets/7347009/16176773/2be9f870-364a-11e6-82f8-4762c360cc71.png)

[my dev env]
```
Windows OS
node v6.2.1
npm 3.9.3
```

個人猜測我本地 api/config.js 有誤，目前它是：
```
export default {
  API_PROTOCOL: 'http',
  API_HOST: 'localhost',
  API_PORT: '8080'
}
```

可提示 api/config.js 應為何?  
Thanks!

**Comment by hcchien** [comment]
這是因為 localhost 沒有跑 api server 的緣故
我們應該要想想提供一個 dev 的 api server 可以用

**Comment by aqutw** [comment]
Thanks for answer.


目前 dev 是直接拿 production api server 的 data 嗎? 若是，也是一個解法 (因為前台大多是 GET 請求).

Or... 
./api/config.js 之於 production api server 的設定內容不便公開  或  網路環境使得外部拿不到 production api server data。

BTW,
master 在 npm run dev 能正常顯示 Home page & 各Category listing page。
但不能見單一文章詳細頁 (url is /a/XXXXX )。<--- 此 priority 小於本issue，故料想不另開 issue，只先見 revamp 新版。

**Comment by hcchien** [comment]
目前 dev 大多在自己的 local 跑 api server
api layer 的 production server 的 schema 跟 revamp 也已經不同了

我會先試著裝一台 dev box 包含 fe 跟 api
之後如果 local 沒有 api layer 應該可以打 dev box

**Comment by hcchien** [comment]
目前應該可以試試把 api 改為打 http://dev.twreporter.org:8080/

**Comment by hcchien** [comment]
對了，如果試過沒問題就可以關掉 issue 了   :D

**Comment by aqutw** [comment]
Yes, got it.  
I think that it should work.

昨晚小試不行。
會再截圖到這 (diff & web screen)。

查看 tags 有 request 成功，
但後面的連鎖 requests 沒有發出 (目前先從我的 config 懷疑，不從 revamp code unfinished )。

待截圖。

**Comment by hcchien** [comment]
也有可能是 import 資料有問題，不過可以先等 screenshot

**Comment by aqutw** [comment]
# step1
Using same dev env OS and do this..
```
git clone today's twreporter-react twreporter-react_dev
cd twreporter-react_dev
git checkout revamp
npm i
```

# step2
```diff
diff --git a/config.js b/config.js
index 2bb545f..ccdbafe 100644
--- a/config.js
+++ b/config.js
@@ -1,6 +1,6 @@
 module.exports = {
   host: process.env.HOST || 'localhost',
   port: process.env.PORT || 3000,
-  apiHost: process.env.APIHOST || 'localhost',
-  apiPort: process.env.APIPORT || 3030
+  apiHost: process.env.APIHOST || 'dev.twreporter.org',
+  apiPort: process.env.APIPORT || 8080
 }
diff --git a/package.json b/package.json
index 30fed0f..fb22892 100644
--- a/package.json
+++ b/package.json
@@ -43,8 +43,8 @@
         "NODE_PATH": "./server",
         "NODE_ENV": "development",
         "PORT": 3000,
-        "APIHOST": "localhost",
-        "APIPORT": 3030,
+        "APIHOST": "dev.twreporter.org",
+        "APIPORT": 8080,
         "APIPROTOCOL": "http"
       }
     },
@@ -53,7 +53,7 @@
       "env": {
         "NODE_PATH": "./api",
         "NODE_ENV": "development",
-        "APIPORT": 3030
+        "APIPORT": 8080
       }
     },
     "watch-client": {
diff --git a/server/config.js b/server/config.js
index 80493b8..1d8cced 100644
--- a/server/config.js
+++ b/server/config.js
@@ -11,8 +11,8 @@ module.exports = Object.assign({
   host: process.env.HOST || 'localhost',
   port: parseInt(process.env.PORT) || 3000,
   apiProtocol: process.env.APIPROTOCOL || 'http',
-  apiHost: process.env.APIHOST || 'localhost',
-  apiPort: parseInt(process.env.APIPORT) || 3030,
+  apiHost: process.env.APIHOST || 'dev.twreporter.org',
+  apiPort: parseInt(process.env.APIPORT) || 8080,
   app: {
     title: '報導者The Reporter',
     description: '報導者致力於具有手作質感的深度報導，並勇於探索網路新工具與呈現方式，重視網路的公共性與開放性，結合各種進步價值與公民力量。'
```
# step3 ./api/config.js 內容
export default {
  API_PROTOCOL: 'http',
  API_HOST: 'dev.twreporter.org',
  API_PORT: '8080'
}

# step4 
`npm run dev`

# result
In browser
![image](https://cloud.githubusercontent.com/assets/7347009/16267043/5fad234a-38ba-11e6-931e-8e09091355ff.png)

Is this useful info?
![image](https://cloud.githubusercontent.com/assets/7347009/16267066/7ded4e02-38ba-11e6-9800-ef78311ad53b.png)

**Comment by hcchien** [comment]
ok, I understand it.

1. you can run 'git checkout .' to revert the files.
2. vim api/config.js with 
`export default {                                                                                                                             
  API_PROTOCOL: 'http',
  API_HOST: 'dev.twreporter.org',
  API_PORT: '8080'
}
`
3.  'npm run dev' to start the server
4. go to http://localhost:3000/a/second

and I will add more test data in the db later

**Comment by aqutw** [comment]
# step1
Followed steps at your previous comment.

# result
The console is outputing continously such as
`Error: listen EADDRINUSE :::3030` and `WEBPACK_CONFIG is not defined`
```
[1] Error: listen EADDRINUSE :::3030
[1]     at Object.exports._errnoException (util.js:1007:11)
[1]     at exports._exceptionWithHostPort (util.js:1030:20)
[1]     at Server._listen2 (net.js:1253:14)
[1]     at listen (net.js:1289:10)
[1]     at Server.listen (net.js:1385:5)
[1]     at EventEmitter.listen (D:\reactWorkSpace\twreporter_dev\node_modules\express\lib\application.js:617:24)
[1]     at Object.<anonymous> (api.js:39:7)
[1]     at Module._compile (module.js:541:32)
[1]     at loader (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:158:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:168:7)
[1] error: Forever detected script exited with code: 1
[1] error: Script restart attempt #49
[0] D:\reactWorkSpace\twreporter_dev\node_modules\babel-core\lib\transformation\file\index.js:591
[0]       throw err;
[0]       ^
[0]
[0] ReferenceError: D:/reactWorkSpace/twreporter_dev/src/components/article/index.js: WEBPACK_CONFIG is not defined
[0]     at eval (eval at <anonymous> (D:\reactWorkSpace\twreporter_dev\node_modules\babel-plugin-webpack-loaders\node_modules\lodash\template.js:224:12), <anonymous>:8:10)
[0]     at PluginPass.CallExpression (D:\reactWorkSpace\twreporter_dev\node_modules\babel-plugin-webpack-loaders\lib\plugin.js:40:69)
[0]     at newFn (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\visitors.js:301:19)
[0]     at NodePath._call (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:76:18)
[0]     at NodePath.call (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:48:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:106:12)
[0]     at TraversalContext.visitQueue (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:167:16)
[0]     at TraversalContext.visitSingle (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:118:19)
[0]     at TraversalContext.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:211:19)
[0]     at Function.traverse.node (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\index.js:161:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:116:19)
[0]     at TraversalContext.visitQueue (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:167:16)
[0]     at TraversalContext.visitMultiple (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:113:17)
[0]     at TraversalContext.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:209:19)
[0]     at Function.traverse.node (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\index.js:161:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:116:19)
[0] error: Forever detected script exited with code: 1
[0] error: Script restart attempt #29
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: listen EADDRINUSE :::3030
[1]     at Object.exports._errnoException (util.js:1007:11)
[1]     at exports._exceptionWithHostPort (util.js:1030:20)
[1]     at Server._listen2 (net.js:1253:14)
[1]     at listen (net.js:1289:10)
[1]     at Server.listen (net.js:1385:5)
[1]     at EventEmitter.listen (D:\reactWorkSpace\twreporter_dev\node_modules\express\lib\application.js:617:24)
[1]     at Object.<anonymous> (api.js:39:7)
[1]     at Module._compile (module.js:541:32)
[1]     at loader (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:158:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:168:7)
[1] error: Forever detected script exited with code: 1
[1] error: Script restart attempt #50
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: listen EADDRINUSE :::3030
[1]     at Object.exports._errnoException (util.js:1007:11)
[1]     at exports._exceptionWithHostPort (util.js:1030:20)
[1]     at Server._listen2 (net.js:1253:14)
[1]     at listen (net.js:1289:10)
[1]     at Server.listen (net.js:1385:5)
[1]     at EventEmitter.listen (D:\reactWorkSpace\twreporter_dev\node_modules\express\lib\application.js:617:24)
[1]     at Object.<anonymous> (api.js:39:7)
[1]     at Module._compile (module.js:541:32)
[1]     at loader (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:158:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:168:7)
[1] error: Forever detected script exited with code: 1
[1] error: Script restart attempt #51
[0] D:\reactWorkSpace\twreporter_dev\node_modules\babel-core\lib\transformation\file\index.js:591
[0]       throw err;
[0]       ^
[0]
[0] ReferenceError: D:/reactWorkSpace/twreporter_dev/src/components/article/index.js: WEBPACK_CONFIG is not defined
[0]     at eval (eval at <anonymous> (D:\reactWorkSpace\twreporter_dev\node_modules\babel-plugin-webpack-loaders\node_modules\lodash\template.js:224:12), <anonymous>:8:10)
[0]     at PluginPass.CallExpression (D:\reactWorkSpace\twreporter_dev\node_modules\babel-plugin-webpack-loaders\lib\plugin.js:40:69)
[0]     at newFn (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\visitors.js:301:19)
[0]     at NodePath._call (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:76:18)
[0]     at NodePath.call (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:48:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:106:12)
[0]     at TraversalContext.visitQueue (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:167:16)
[0]     at TraversalContext.visitSingle (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:118:19)
[0]     at TraversalContext.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:211:19)
[0]     at Function.traverse.node (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\index.js:161:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:116:19)
[0]     at TraversalContext.visitQueue (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:167:16)
[0]     at TraversalContext.visitMultiple (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:113:17)
[0]     at TraversalContext.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:209:19)
[0]     at Function.traverse.node (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\index.js:161:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:116:19)
[0] error: Forever detected script exited with code: 1
[0] error: Script restart attempt #30
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: listen EADDRINUSE :::3030
[1]     at Object.exports._errnoException (util.js:1007:11)
[1]     at exports._exceptionWithHostPort (util.js:1030:20)
[1]     at Server._listen2 (net.js:1253:14)
[1]     at listen (net.js:1289:10)
[1]     at Server.listen (net.js:1385:5)
[1]     at EventEmitter.listen (D:\reactWorkSpace\twreporter_dev\node_modules\express\lib\application.js:617:24)
[1]     at Object.<anonymous> (api.js:39:7)
[1]     at Module._compile (module.js:541:32)
[1]     at loader (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:158:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:168:7)
[1] error: Forever detected script exited with code: 1
[1] error: Script restart attempt #52
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: listen EADDRINUSE :::3030
[1]     at Object.exports._errnoException (util.js:1007:11)
[1]     at exports._exceptionWithHostPort (util.js:1030:20)
[1]     at Server._listen2 (net.js:1253:14)
[1]     at listen (net.js:1289:10)
[1]     at Server.listen (net.js:1385:5)
[1]     at EventEmitter.listen (D:\reactWorkSpace\twreporter_dev\node_modules\express\lib\application.js:617:24)
[1]     at Object.<anonymous> (api.js:39:7)
[1]     at Module._compile (module.js:541:32)
[1]     at loader (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:158:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:168:7)
[1] error: Forever detected script exited with code: 1
[1] error: Script restart attempt #53
[0] D:\reactWorkSpace\twreporter_dev\node_modules\babel-core\lib\transformation\file\index.js:591
[0]       throw err;
[0]       ^
[0]
[0] ReferenceError: D:/reactWorkSpace/twreporter_dev/src/components/article/index.js: WEBPACK_CONFIG is not defined
[0]     at eval (eval at <anonymous> (D:\reactWorkSpace\twreporter_dev\node_modules\babel-plugin-webpack-loaders\node_modules\lodash\template.js:224:12), <anonymous>:8:10)
[0]     at PluginPass.CallExpression (D:\reactWorkSpace\twreporter_dev\node_modules\babel-plugin-webpack-loaders\lib\plugin.js:40:69)
[0]     at newFn (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\visitors.js:301:19)
[0]     at NodePath._call (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:76:18)
[0]     at NodePath.call (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:48:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:106:12)
[0]     at TraversalContext.visitQueue (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:167:16)
[0]     at TraversalContext.visitSingle (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:118:19)
[0]     at TraversalContext.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:211:19)
[0]     at Function.traverse.node (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\index.js:161:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:116:19)
[0]     at TraversalContext.visitQueue (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:167:16)
[0]     at TraversalContext.visitMultiple (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:113:17)
[0]     at TraversalContext.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:209:19)
[0]     at Function.traverse.node (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\index.js:161:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:116:19)
[0] error: Forever detected script exited with code: 1
[0] error: Script restart attempt #31
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: listen EADDRINUSE :::3030
[1]     at Object.exports._errnoException (util.js:1007:11)
[1]     at exports._exceptionWithHostPort (util.js:1030:20)
[1]     at Server._listen2 (net.js:1253:14)
[1]     at listen (net.js:1289:10)
[1]     at Server.listen (net.js:1385:5)
[1]     at EventEmitter.listen (D:\reactWorkSpace\twreporter_dev\node_modules\express\lib\application.js:617:24)
[1]     at Object.<anonymous> (api.js:39:7)
[1]     at Module._compile (module.js:541:32)
[1]     at loader (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:158:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:168:7)
[1] error: Forever detected script exited with code: 1
[1] error: Script restart attempt #54
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: listen EADDRINUSE :::3030
[1]     at Object.exports._errnoException (util.js:1007:11)
[1]     at exports._exceptionWithHostPort (util.js:1030:20)
[1]     at Server._listen2 (net.js:1253:14)
[1]     at listen (net.js:1289:10)
[1]     at Server.listen (net.js:1385:5)
[1]     at EventEmitter.listen (D:\reactWorkSpace\twreporter_dev\node_modules\express\lib\application.js:617:24)
[1]     at Object.<anonymous> (api.js:39:7)
[1]     at Module._compile (module.js:541:32)
[1]     at loader (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:158:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:168:7)
[1] error: Forever detected script exited with code: 1
[1] error: Script restart attempt #55
[0] D:\reactWorkSpace\twreporter_dev\node_modules\babel-core\lib\transformation\file\index.js:591
[0]       throw err;
[0]       ^
[0]
[0] ReferenceError: D:/reactWorkSpace/twreporter_dev/src/components/article/index.js: WEBPACK_CONFIG is not defined
[0]     at eval (eval at <anonymous> (D:\reactWorkSpace\twreporter_dev\node_modules\babel-plugin-webpack-loaders\node_modules\lodash\template.js:224:12), <anonymous>:8:10)
[0]     at PluginPass.CallExpression (D:\reactWorkSpace\twreporter_dev\node_modules\babel-plugin-webpack-loaders\lib\plugin.js:40:69)
[0]     at newFn (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\visitors.js:301:19)
[0]     at NodePath._call (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:76:18)
[0]     at NodePath.call (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:48:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:106:12)
[0]     at TraversalContext.visitQueue (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:167:16)
[0]     at TraversalContext.visitSingle (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:118:19)
[0]     at TraversalContext.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:211:19)
[0]     at Function.traverse.node (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\index.js:161:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:116:19)
[0]     at TraversalContext.visitQueue (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:167:16)
[0]     at TraversalContext.visitMultiple (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:113:17)
[0]     at TraversalContext.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\context.js:209:19)
[0]     at Function.traverse.node (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\index.js:161:17)
[0]     at NodePath.visit (D:\reactWorkSpace\twreporter_dev\node_modules\babel-traverse\lib\path\context.js:116:19)
[0] error: Forever detected script exited with code: 1
[0] error: Script restart attempt #32
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: listen EADDRINUSE :::3030
[1]     at Object.exports._errnoException (util.js:1007:11)
[1]     at exports._exceptionWithHostPort (util.js:1030:20)
[1]     at Server._listen2 (net.js:1253:14)
[1]     at listen (net.js:1289:10)
[1]     at Server.listen (net.js:1385:5)
[1]     at EventEmitter.listen (D:\reactWorkSpace\twreporter_dev\node_modules\express\lib\application.js:617:24)
[1]     at Object.<anonymous> (api.js:39:7)
[1]     at Module._compile (module.js:541:32)
[1]     at loader (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:158:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (D:\reactWorkSpace\twreporter_dev\node_modules\babel-register\lib\node.js:168:7)
[1] error: Forever detected script exited with code: 1
[1] error: Script restart attempt #56
```

**Comment by aqutw** [comment]
新的實驗結果似乎更不佳。
新的頁面全不可見、舊的實驗有header&footer。 @.@

**Comment by hcchien** [comment]
你現在 git diff 如何?

**Comment by aqutw** [comment]
git diff 為空。
( 因為全checkout掉了  &  api/config.js 是 gitignore。)

**Comment by aqutw** [comment]
你那邊乾淨的clone + 只新增 api/config.js (內容如上) 是 ok 嗎?  若是，我先 close 這個 issue 好了...

**Comment by hcchien** [comment]
我剛剛 pull 最新的 code 加上這個 config.js 應該是好的

**Comment by aqutw** [comment]
Tested on Ubuntu(Virtualbox) with node 6.2.1, issue still exists.

Let me close this issue for now, I could try more while I have time recently ^_^.

**Comment by nickhsine** [comment]
Step2 的package.json不要改成8080 port。
3030 port是FE api endpoint 的 port，8080 port是 FE 去後面拿資料的時候開的 port。
我明天試試看node 6。

**Comment by nickhsine** [comment]
@aqutw 
我剛剛測試了，node@6.2.1 是ok的。

至於你發生這個問題是正常的，因為 ```revamp branch``` 目前還在改 article page 的部分，所以首頁的部分還有些問題。
你看到的錯誤是因為 CMS 還沒有編輯 category(評論、專題) ，然而 ```index page``` 就是要根據 category 去拿 articles 。（我剛剛把這兩個category加上去了，所以現在應該不會只有了header and footer了。）
![image](https://cloud.githubusercontent.com/assets/3000343/16289918/fcc114ea-392b-11e6-9cc4-63b076730bb4.png)

[CMS](http://dev.twreporter.org/keystone/)
上面是我們 dev 的 cms，
我幫你開了一組帳號，
帳號/密碼是 aqutw@gmail.com/aqutw   (email/密碼的部分你在自己改)
你可以在CMS上面新增你想要測試的東西。

### 結論
你就只需要新增 api/config.js，
```
export default {
API_PROTOCOL: 'http',
API_HOST: 'dev.twreporter.org',
API_PORT: '8080'
}
```
其餘的應該都沒有問題了。

**Comment by aqutw** [comment]
Looks coool,   I will try later ( I already change my CMS password. ),   thanks supports!
